########## How To Use Docker Image ###############
##
##  Docker hub link:
##  Description: This docker container is for the Zuul API gateway server.
##################################################
FROM openjdk:jre

ADD build/libs/gateway-0.0.1-SNAPSHOT.jar /app.jar